### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [SleeplessDevelopment/Bamboozled#1]
Crashes when i launch game. Seems to only happen when I am missing hwlya. maybe add a check if the mod is not on? or simply make it a required dependency

https://pastebin.com/kVuBmhBq

**Comment by ChloeDawn** [comment]
Fixed in [1.0.4](https://minecraft.curseforge.com/projects/bamboozled/files/2526883)
