### ISSUE TITLE
Worldgen crash

### ISSUE THREAD

**Issue by Kriiks** [SleeplessDevelopment/Bamboozled#2]
Still crashing server while generating new chunks. Version 1.12-1.0.9

[crash-2018-02-07_15.12.54-server.txt](https://github.com/SleeplessDevelopment/Bamboozled/files/1703399/crash-2018-02-07_15.12.54-server.txt)

**Comment by ChloeDawn** [comment]
~~Mojang hates servers apparently, I'll fix this soon~~
I overlooked something and feel dumb now.

**Comment by Kriiks** [comment]
Thank you!
