### ISSUE TITLE
Excessive halite generation causing performance issues

### ISSUE THREAD

**Issue by ghost** [SleeplessDevelopment/Bamboozled#3]
Due to how Halite spawns within 3 blocks of flowing or source water, large sections of the ocean floor are converted into Halite. If you're not already aware, translucent blocks are more taxing to render, and as a result I suffer lag whenever I look into the ocean. Is there a way you can turn off this generation method in ocean biomes (either entirely in these biomes, or only permit spawning below the common sea level for each ocean biome such that it doesn't generate on the ocean floor)?

**Comment by ChloeDawn** [comment]
My implementation for the halite generation is really bad, I was half-expecting this to happen eventually.. I'll rewrite it to generate like regular ore clusters, I think.

**Comment by ghost** [comment]
I think the way you have it generating currently is really cool! I like how different it is and how interesting that makes looking for it, and how it improves the caving experience. The only problem is in ocean biomes, and I think that's the only area that needs to be addressed (as far as I can see, as a user, that is).

**Comment by ChloeDawn** [comment]
This has been resolved in [1.12-1.1.0](https://minecraft.curseforge.com/projects/bamboozled/files/2546272). World generation has been rewritten to be more performant, and Halite now renders solid when using Fast graphics - there is a config to force translucent rendering if desired. Apologies for taking so long to resolve this... I have a bad habit of procrastinating things.
